// <auto-generated />
using CoreWebAppMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreWebAppMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240410025041_AddImagePathColumnToFriendsTable")]
    partial class AddImagePathColumnToFriendsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreWebAppMVC.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@test.com.ar",
                            ImagePath = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/2fabe02d-b3de-4453-a877-3e57a9266b30/deyynsc-7673267a-f883-4f9f-a2e3-fd4733c9f30c.png/v1/fill/w_730,h_1095,q_70,strp/nezuko_s_demon_form_by_oddityillustrations_deyynsc-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzYwMCIsInBhdGgiOiJcL2ZcLzJmYWJlMDJkLWIzZGUtNDQ1My1hODc3LTNlNTdhOTI2NmIzMFwvZGV5eW5zYy03NjczMjY3YS1mODgzLTRmOWYtYTJlMy1mZDQ3MzNjOWYzMGMucG5nIiwid2lkdGgiOiI8PTI0MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.nsUBfTt3zLKrf_1ekFBFgYiLTh5svH0AZPw9TZQVop4",
                            Name = "Test2",
                            Skill = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
